version: "3"
services: 
  front:
    restart: always
    image: okakyo/go-front
    build: 
      context: "./front"
      target: "base"
    tty: true
    volumes:
      - ./front:/app/go/base
    depends_on:
      - db 
    ports:
      - 3000:3000
    command: "npm run dev"
  
  db:
    image: mariadb:focal
    container_name: goserver_testdb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MUSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    
  ml-server:
    restart: always
    build: mlserver
    image: okakyo/ml-server
    container_name: goserver_ml-server
    tty: true
    volumes:
      - ./mlserver/src:/src/server
      - ./mlserver/tests:/src/tests
    depends_on:
      - db
    ports:
      - 8000:8000
    command: "uvicorn main:app --reload --host 0.0.0.0"


  
